# Generated by Django 4.1.3 on 2022-12-13 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('middle_name', models.CharField(max_length=50, verbose_name='Отчество')),
                ('gender', models.CharField(max_length=1, verbose_name='Пол')),
                ('birth_date', models.DateField(default=datetime.date(2000, 1, 1), verbose_name='Дата рождения')),
                ('card_id', models.SmallIntegerField(verbose_name='Номер карточки')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Дата изменения')),
                ('disabled', models.BooleanField(default=False, verbose_name='Есть ли инвалидность')),
            ],
        ),
    ]
