# Generated by Django 4.1.3 on 2022-12-13 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_medics_alter_patient_card_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='Категория')),
                ('service', models.CharField(max_length=50, verbose_name='Оказываемая услуга')),
                ('enroll_year', models.IntegerField(verbose_name='Год устройства')),
            ],
        ),
        migrations.AlterField(
            model_name='medics',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.category', verbose_name='Категория'),
        ),
    ]
