# Generated by Django 4.1.3 on 2022-12-13 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_category_alter_medics_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='medics',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='medics',
            name='category',
            field=models.CharField(max_length=50, verbose_name='Категория'),
        ),
    ]
