# Generated by Django 4.1.3 on 2022-12-13 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_medics_cat_alter_medics_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='cat',
        ),
    ]
