# Generated by Django 4.1.3 on 2022-12-13 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_rename_category_category_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=50, verbose_name='Категория')),
                ('service', models.CharField(max_length=50, verbose_name='Оказываемая услуга')),
                ('enroll_year', models.IntegerField(verbose_name='Год устройства')),
            ],
        ),
        migrations.RemoveField(
            model_name='medics',
            name='cat',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='medics',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.group', verbose_name='Группа'),
        ),
    ]
