# Generated by Django 4.1.3 on 2022-12-13 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_group_remove_medics_cat_delete_category_medics_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group',
            field=models.CharField(max_length=50, verbose_name='Группа'),
        ),
    ]
