# Generated by Django 4.1.3 on 2022-12-13 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_alter_group_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='group',
            new_name='grouptype',
        ),
        migrations.RenameField(
            model_name='medics',
            old_name='group',
            new_name='grouptype',
        ),
    ]
