# Generated by Django 4.1.3 on 2022-12-13 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_rename_group_group_grouptype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grouptype', models.CharField(max_length=50, verbose_name='Группа')),
                ('service', models.CharField(max_length=50, verbose_name='Оказываемая услуга')),
                ('enroll_year', models.IntegerField(verbose_name='Год устройства')),
            ],
        ),
        migrations.AlterField(
            model_name='medics',
            name='grouptype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.grouptype', verbose_name='Группа'),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
