# Generated by Django 4.1.3 on 2022-12-13 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_grouptype_alter_medics_grouptype_delete_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medics',
            name='category',
        ),
        migrations.AlterField(
            model_name='grouptype',
            name='grouptype',
            field=models.CharField(max_length=50, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='medics',
            name='grouptype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.grouptype', verbose_name='Категория'),
        ),
    ]
