# Generated by Django 4.1.3 on 2022-12-13 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_remove_medics_category_alter_grouptype_grouptype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouptype',
            name='enroll_year',
        ),
    ]
