# Generated by Django 4.1.3 on 2022-12-13 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_remove_grouptype_enroll_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medics',
            name='grouptype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.grouptype', verbose_name='Категория'),
        ),
    ]
