# Generated by Django 4.1.3 on 2022-12-13 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0012_alter_medics_grouptype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grouptype',
            options={'ordering': ['grouptype'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='medics',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Врач', 'verbose_name_plural': 'Врачи'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'Пациент', 'verbose_name_plural': 'Пациенты'},
        ),
    ]
