# Generated by Django 4.1.3 on 2022-12-13 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0013_alter_grouptype_options_alter_medics_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medics',
            name='is_workin',
            field=models.BooleanField(default=True, verbose_name='Работает на данный момент'),
        ),
    ]
