# Generated by Django 4.1.3 on 2022-12-14 23:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0016_alter_medics_works_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='medics',
            name='birth_date',
            field=models.DateField(default=datetime.date(2000, 1, 1), verbose_name='Дата рождения'),
        ),
    ]
