# Generated by Django 4.1.3 on 2022-12-14 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0017_medics_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='medics',
            name='slug',
            field=models.SlugField(max_length=255, null=True, verbose_name='URL'),
        ),
    ]
