# Generated by Django 4.1.3 on 2022-12-14 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0018_medics_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medics',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
